#!/usr/bin/env bash

# Script paths
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_DIR="$CURRENT_DIR/script"

# Load configuration
source "$CURRENT_DIR/config"

echo "** Running backup scripts for ${APP_NAME} **"
date

cd $APP_ROOT

DB_ENV="DB_NAME=$DB_NAME DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD DB_HOST=$DB_HOST DB_ADAPTER=$DB_ADAPTER"
AWS_ENV="AWS_CLI_COMMAND=$AWS_CLI_COMMAND AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"

echo "** Backing up database **"
DB_BACKUP_NAME="db-backup-$(date +%F-%H-%M-%S)"
DB_BACKUP_PATH="$BACKUP_TMP/$DB_BACKUP_NAME.dump"
eval "$DB_ENV $SCRIPT_DIR/backup_db $DB_BACKUP_PATH"

echo "** Compressing database **"
DB_BACKUP_TAR="$BACKUP_TMP/$DB_BACKUP_NAME.tar.gz"
eval "cd $BACKUP_TMP && tar -cvzf $DB_BACKUP_TAR $DB_BACKUP_NAME.dump && rm $DB_BACKUP_PATH"

echo "** Copying database to Amazon S3 **"
eval "$AWS_ENV AWS_BACKUP_PATH=$AWS_DB_BACKUP_PATH $SCRIPT_DIR/backup_db_to_s3 $DB_BACKUP_TAR"

echo "** Syncing folders to Amazon S3 **"
eval "$AWS_ENV AWS_BACKUP_PATH=$AWS_FILE_BACKUP_PATH $SCRIPT_DIR/sync_files_to_s3 $BACKUP_FOLDERS"