#!/usr/bin/env bash
#
# Pass the folders to be synced as arguments:
# ./sync_files_to_s3 public/images public/uploads
#
# The AWS configuration should be set up in the env variables:
# AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION
#
# AWS_BACKUP_PATH should contain the bucket and a prefix if required, with no trailing slash
# If the bucket is called 'backup-bucket', AWS_BACKUP_PATH should be set to 'backup-bucket'
# If the backups should be in the folder 'files', it should be set to 'backup-bucket/files'
#
# This script syncs the folders to the S3 bucket, deleting any removed files. Versioning should
# be enabled on the bucket for proper backing up

for FROM_PATH in $@
do
  S3_PATH="s3://$AWS_BACKUP_PATH/$FROM_PATH"
  echo -e "\n** Syncing $FROM_PATH to $S3_PATH **"

  aws s3 sync $FROM_PATH $S3_PATH --delete
done
